### ISSUE TITLE
 add additional navbar under analysis

### ISSUE THREAD

**Issue by quantintell** [BugzTheBunny/streamlit-navbar-flaskless#1]
Hello BugzTheBunny:

Thanks for sharing streamlit-navbar-flaskless codes.

May I ask you a how to do the following thing:

at you sample codes main.py, assuming at under "analysis" I want to add additional navbar under analysis,
for example, "eda - marketing", "eda - financial", or more, etc.

Actually, just like SETTINGS = {
    'OPTIONS':'options',
    'CONFIGURATION':'configuration'
}

you have two options under SETTINGS.

I want to know or learn how to add additional navbars under the analysis navbar.

Thanks

**Comment by BugzTheBunny** [comment]
Hi! Sorry for the late response.

In order to add, you need to follow the way I built it with, or create a different convention of your own.

"my way" you can:

1. Add it to the Settings / Navbar Paths.
2. Create a view for it with an initialization function that will be called when the navigation matches.
3. Add it to the navigation (main.py).

**Comment by quantintell** [comment]
Hello BugzTheBunny/streamlit-navbar-flaskless:

Thanks for your email and instructions.
Also, appreciate your sharing codes.

Thanks,
